AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Resources:
  nodeVideoStreamService:
    Type: AWS::Serverless::Function
    Properties:
      Handler: aws-lambda.handler
      Runtime: nodejs6.10
      CodeUri: ./dist
      MemorySize: 512
      Timeout: 10
      Policies: AmazonDynamoDBFullAccess
      Events:
        nodeVideoStreamApiGateway:
          Type: Api
          Properties:
            Path: /videostreamapi
            Method: ANY
  active-users:
    Type: AWS::DynamoDB::Table
    Properties: 
      AttributeDefinitions: 
        - AttributeName: username
          AttributeType: S
      KeySchema: 
        - AttributeName: username
          KeyType: HASH
      ProvisionedThroughput: 
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5