AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Resources:
  startVideo:
    Type: AWS::Serverless::Function
    Properties:
      Handler: index-aws-lambda.handler
      Runtime: nodejs6.10
      CodeUri: ./dist
      MemorySize: 512
      Timeout: 10
      Policies: AmazonDynamoDBFullAccess
      Events:
        nodeVideoStreamApiGateway:
          Type: Api
          Properties:
            Path: /startVideo
            Method: GET
      Environment:
        Variables:
          TABLE_NAME: !Ref activeUsers
  endVideo:
    Type: AWS::Serverless::Function
    Properties:
      Handler: index-aws-lambda.handler
      Runtime: nodejs6.10
      CodeUri: ./dist
      MemorySize: 512
      Timeout: 10
      Policies: AmazonDynamoDBFullAccess
      Events:
        nodeVideoStreamApiGateway:
          Type: Api
          Properties:
            Path: /endVideo
            Method: GET
      Environment:
        Variables:
          TABLE_NAME: !Ref activeUsers
  count:
    Type: AWS::Serverless::Function
    Properties:
      Handler: index-aws-lambda.handler
      Runtime: nodejs6.10
      CodeUri: ./dist
      MemorySize: 512
      Timeout: 10
      Policies: AmazonDynamoDBFullAccess
      Events:
        nodeVideoStreamApiGateway:
          Type: Api
          Properties:
            Path: /count
            Method: GET
      Environment:
        Variables:
          TABLE_NAME: !Ref activeUsers
  activeUsers:
    Type: AWS::DynamoDB::Table
    Properties: 
      AttributeDefinitions: 
        - AttributeName: username
          AttributeType: S
      KeySchema: 
        - AttributeName: username
          KeyType: HASH
      ProvisionedThroughput: 
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5