AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Resources:
  nodeVideoStreamService:
    Type: AWS::Serverless::Function
    Properties:
      Handler: index.aws-lambda.handler
      Runtime: nodejs6.10
			CodeUri: ./src
			MemorySize: 512
      Timeout: 10
      Policies: AmazonDynamoDBFullAccess
      Events:
        nodeVideoStreamApiGateway:
          Type: Api
          Properties:
            Path: /myFirstFunction
            Method: ANY
  TableName:
    Type: AWS::DynamoDB::Table
    Properties: 
      AttributeDefinitions: 
        - AttributeName: id
          AttributeType: S
      KeySchema: 
        - AttributeName: id
          KeyType: HASH
      ProvisionedThroughput: 
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5